---
title: "Study 2 Cleaning"
author: "Ramiro Casó - Incae Business School"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
```

## Loading the data

```{r}
study2_data <- read_csv("pilot_b.csv")
#View(study2_data)

s2data <- study2_data[3:nrow(study2_data), c(6, 9, 18:152)] #select the columns
exclude_cols <- grep("First Click|Last Click|Click Count", colnames(study2_data))
selected_cols <- setdiff(c(6, 9, 18:152), exclude_cols)
s2data <- study2_data[3:nrow(study2_data), selected_cols]
s2data <- filter(s2data,Consent == 1)

```

## IV Labels as factors

```{r}
s2data$text_type <- as.factor(s2data$text_type)
s2data$wta_moment <- as.factor(s2data$wta_moment)

```



## Subjective knowledge scale

```{r}
sk_df <- s2data[, c(2, grep("^sk", colnames(s2data)))] %>%
  mutate(across(starts_with("sk"), as.numeric))

sk_df <- mutate(sk_df,
                ave_sk_t1 = rowMeans(sk_df[, 2:4], na.rm = TRUE),
                ave_sk_t2 = rowMeans(sk_df[, 5:7], na.rm = TRUE),
                ave_sk_t3 = rowMeans(sk_df[, 8:10], na.rm = TRUE))

```



## Objective Scale Data

```{r}
ok_df <- s2data[, c(2, grep("^ok", colnames(s2data)))[!grepl("time_Page Submit", colnames(s2data)[c(2, grep("^ok", colnames(s2data)))])]]

ok_df[, -1] <- lapply(ok_df[, -1], as.numeric) #This makes all the columns numeric except the ID

ok_df <- mutate(ok_df, total_ok = rowSums(ok_df[, 2:10], na.rm = TRUE)) #This calculates the total score for each participant
```

## WTA scale data

```{r}
wta_df <- s2data[, c(2, grep("^wta", colnames(s2data)))] %>%
  mutate(across(starts_with("wta-"), as.numeric)) %>%
  mutate(ave_wta = rowMeans(.[, 2:4], na.rm = TRUE))
wta_df <- wta_df[,-5]

```

## Time reading texts

```{r}
text_times <- s2data[, c(2,7:24,55)]
text_times[, c(2:19)] <- lapply(text_times[, c(2:19)], as.numeric)
text_times <- text_times %>%
  mutate(ave_time = rowMeans(.[, 2:19], na.rm = TRUE))
#text_times <- text_times [,-1]
write.csv(text_times,"text_times.csv")

```

## Demographics

```{r}
# Selecting columns, converting to numeric, and renaming
demographics <- s2data %>%
  select(1, 2, 52, 53, 55, 56) %>%
  mutate_at(vars(1, 3, 4), as.numeric) %>%
  rename(diet_freq = "demo-1", bmi = "demo-2")  
```


## Joining everything: 
```{r}

# Joining the data sets

joined_df_b <- inner_join(ok_df, sk_df, by = "ResponseId") %>% 
  inner_join(wta_df, by = "ResponseId") %>%
  inner_join(text_times,by = "ResponseId")  %>%
  inner_join(demographics,by = "ResponseId")

# removing duplicates 

joined_df_b <- joined_df_b[,-51]

# Renaming the columns to facilitate understanding

joined_df_b <- joined_df_b %>%
  rename(
    sk_t1_1 = `sk-pretext-matrix_1`,
    sk_t1_2 = `sk-pretext-matrix_2`,
    sk_t1_3 = `sk-pretext-matrix_3`,
    sk_t2_1 = `sk-postext-matrix_1`,
    sk_t2_2 = `sk-postext-matrix_2`,
    sk_t2_3 = `sk-postext-matrix_3`,
    sk_t3_1 = `sk-posok-matrix_1`,
    sk_t3_2 = `sk-posok-matrix_2`,
    sk_t3_3 = `sk-posok-matrix_3`,
    text_type = text_type.x,
    duration_sec = `Duration (in seconds)` 
  ) %>%
  rename_with(~ gsub("_Page Submit", "", .), contains("_Page Submit"))

# Creating the new variables I would need. 

joined_df_b <- joined_df_b %>%
  mutate(delta_sk2_sk1 = ave_sk_t2 - ave_sk_t1,
         delta_sk3_sk2 = ave_sk_t3 - ave_sk_t2,
         delta_sk3_sk1 = ave_sk_t3 - ave_sk_t1,
         duration_min = duration_sec / 60,
         pilot = as.factor("pilot_b")
  )

pilot_final <- rbind(joined_df_a, joined_df_b)

write.csv(pilot_final, "study2b_total.csv", row.names = FALSE)

```


